// demoPlatform
export const FETCH_DEMO_PLATFORM = 'FETCH_DEMO_PLATFORM'
export const GET_DEMO_PLATFORM = 'GET_DEMO_PLATFORM'
export const ADD_DEMO_PLATFORM = 'ADD_DEMO_PLATFORM'
export const UPDATE_DEMO_PLATFORM = 'UPDATE_DEMO_PLATFORM'
export const REMOVE_DEMO_PLATFORM = 'REMOVE_DEMO_PLATFORM'

// demoTree
export const FETCH_DEMO_TREE = 'FETCH_DEMO_TREE'
